sudo: false

language: node_js

node_js:
  - 9
  - 8

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

after_success:
  - yarn deploy # // TODO: is this redundant from below, also do i need to add back npm run coveralls?
  - yarn semantic-release

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
