sudo: false

language: node_js

node_js:
  - 9
  - 8
  - 7
  - 6

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

after_success:
  - npm run build
  - npm run coveralls
  - npm run semantic-release

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
